name: grace
description: An open-source, cross-platform collection management application
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.1.5 <4.0.0'

dependencies:
    cloud_firestore: ^4.12.2
    firebase_core: ^2.21.0
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.1.0
    go_router: ^12.1.1
    google_fonts: ^6.1.0
    http: ^1.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1
    test: ^1.24.9
    integration_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - .env
        - assets/images/brand-fill.png
